### PR TITLE
Fixed KindleGen not working on Windows

### PR DESCRIPTION
**Pull request by jdtcoder**
- Added mac and windows version of kindlegen

Notes: untested on linux and mac

### CODE REVIEW

**Comment by dipu-bd** [comment]
Nice! I was planning fix the issue, but could not make enough time. This pull request was right on time.

**Comment by dipu-bd** [comment]
The new executable for kindlegen is giving me `PermissionError: [Errno 13] Permission denied` on Linux. Although running `sudo chmod u+x kindlegen-linux` fixes the error, it is not a permanent solution.

I am trying to find alternatives. I think it will probably be better to let the users use their installed kindlegen.

**Comment by jdtcoder** [comment]
@dipu-bd glad to help. Was it working fine before my I changed it?

**Comment by dipu-bd** [comment]
Nope. Your change did not broke anything. It just pointed a fault out.

**Comment by jdtcoder** [comment]
@dipu-bd got it.

**Pull request merged**
