### PR TITLE
Add boxnovel.com as new source

### PR DESCRIPTION
**Pull request by yudilee**
I add new source for boxnovel.com.

### CODE REVIEW

**Comment by dipu-bd** [comment]
Good to see a new source! It pains me that I have not been getting any free time lately to invest on this project. I have uploaded a new version to *pypi* merging this pull request: https://pypi.org/project/ebook-crawler/

**Comment by yudilee** [comment]
Thanks a lot for merge this pull request. I have already have new
source(novelplanet) but I have to use cfscrape to get the source code
instead of using requests because of usage of antibot on this site. May I
add pull request on this code because it will add new requirement for this
app. Please gave me suggestion on this. Should I pull request first or do
you have any workaround on this matter.

Best Regard

Yudi Lee

**Comment by dipu-bd** [comment]
Cloudflare is tricky. It checks javascript support. `cfscrape` uses node.js to bypass the anti-bot check. So, user must have node.js installed in their PC.

I do not think this is a problem. If someone wants to download particularly from novelplanent, they should be prompt to have `node.js` installed.

Make your pull request to the `dev` branch. I have to review it before merging with `master`.

**Comment by yudilee** [comment]
yes, user should install node.js in their pc to use it. in also use it in binding file to get cover page for the novel. i will try to create branch and upload it. thanks for your reply.

**Pull request merged**
